---
title: "Material de Estudio"
format:
  html:
    toc: true
    smooth-scroll: true
---

# 

Bienvenido al Repositorio de **Laboratorios y Materiales Pr치cticos** del curso de *Econometr칤a FEN-UAH*.\
Aqu칤 encontrar치s gu칤as paso a paso en Rstudio respaldadas con teoria y conceptos escenciales para el curso que acompa침an el aprendizaje aplicado de la econometr칤a, desde regresi칩n simple hasta modelos avanzados.

Cada laboratorio se puede abrir directamente en formato HTML renderizado desde RStudio/Quarto.\
Los documentos que contengan las siglas **"epg"** corresponden al curso *Econometr칤a para la Gesti칩n*, mientras que los **"ec"** pertenecen a *Econometr칤a (menci칩n Econom칤a)*.

## Laboratorios

::::::::::::: labs-grid
::: lab-card
### Lab 1_epg: Introducci칩n y Estad칤stica Descriptiva

Importaci칩n de datos, tablas de frecuencia y medidas descriptivas.\
[Ver Laboratorio](labs/lab01_epg.html){.btn}
:::

::: lab-card
### Lab 2_epg: Regresi칩n Lineal Simple

Estimaci칩n e interpretaci칩n del modelo OLS b치sico.\
[Ver Laboratorio](labs/lab02_epg.html){.btn}
:::

::: lab-card
### Lab 3_epg: Regresi칩n Lineal M칰ltiple

Extensi칩n del modelo con variables adicionales y an치lisis de supuestos.\
[Ver Laboratorio](labs/lab03_epg.html){.btn}
:::

::: lab-card
### Lab 4_epg: Usos y aplicaciones de RLM

Otras funciones para estudiar la regresi칩n m칰ltiple, Eliminaci칩n de variables irrelevantes, Regresi칩n polinomial, etc. \
[Ver Laboratorio](labs/lab04_epg.html){.btn}
:::

::: lab-card
### Lab 5_epg: Modelo Logit-Probit

Motivaci칩n, teor칤a y aplicaci칩n de logit y probit.\
[Ver Laboratorio](labs/lab05_epg.html){.btn}
:::
:::::::::::::

------------------------------------------------------------------------

> 游눠 *Cada laboratorio est치 alojado en la carpeta `labs/` y utiliza los datos correspondientes del directorio `labs/data_epg/`.\
> El sitio se actualiza autom치ticamente cuando los archivos `.qmd` se renderizan a HTML. Esto lo puedes encontrar directamente en el GitHub del sitio web.*
