---
title: "Econometría para la Gestión"
format:
  html:
    toc: false
    smooth-scroll: true
---


## Laboratorios

Objetivos:

-   Introducir conceptos de **programación en R/Quarto**,\
-   Practicar **estimadores econométricos** vistos en el curso,\
-   Desarrollar **intuición aplicada** a partir de datos reales.

A continuación se presenta un listado completo de los laboratorios, disponibles en tres formatos: **HTML** y **PDF**.

1. **Capítulo 1 – Introducción y estadística descriptiva**  
   [HTML](labs_epg/lab01_epg.html){target="_blank"} <a href="labs_epg/lab01_epg.pdf" download>PDF</a>

2. **Capítulo 2 – Correlación y regresión lineal simple**  
   [HTML](labs_epg/lab02_epg.html){target="_blank"} <a href="labs_epg/lab02_epg.pdf" download>PDF</a>

3. **Capítulo 3 – Regresión múltiple**  
   [HTML](labs_epg/lab03_epg.html){target="_blank"} <a href="labs_epg/lab03_epg.pdf" download>PDF</a>

4. **Capítulo 4 – Uso avanzado de la regresión múltiple**  
   [HTML](labs_epg/lab04_epg.html){target="_blank"} <a href="labs_epg/lab04_epg.pdf" download>PDF</a>

5. **Capítulo 5 – Logit y otros análisis**  
   [HTML](labs_epg/lab05_epg.html){target="_blank"} <a href="labs_epg/lab05_epg.pdf" download>PDF</a>

6. **Capítulo 6 – Componentes principales**  
   [HTML](labs_epg/lab06_epg.html){target="_blank"} <a href="labs_epg/lab06_epg.pdf" download>PDF</a>

7. **Capítulo 7 – Análisis factorial (PCA ampliado)**  
   [HTML](labs_epg/lab07_epg.html){target="_blank"} <a href="labs_epg/lab07_epg.pdf" download>PDF</a>
